// Original, self-contained stdin/stdout challenges. Each day has a six-week pool.
const P = (day, title, topic, prompt, input, output, cases, hint) => ({ day, title, topic, prompt, input, output, cases: cases.map(([stdin, expected]) => ({ stdin, expected })), hint });
export const problems = [
  // Monday — warm-up
  P(0,'Pair Sum','Arrays','Given a list of integers and a target, print the zero-based indices of the first pair whose values add to the target. Scan left to right; for each position choose the earliest earlier matching index. A pair is guaranteed.','Line 1: integers separated by spaces. Line 2: target integer.','Two indices, smaller first.',[['2 7 11 15\n9','0 1'],['3 3\n6','0 1'],['1 4 2 3\n5','0 1']],'Remember values you have already seen.'),
  P(0,'Reverse Words','Strings','Reverse the order of words in a sentence. Collapse repeated spaces and omit leading or trailing spaces.','One line of text.','Words in reverse order, separated by one space.',[['  the sky is blue  ','blue is sky the'],['a   good example','example good a']],'Split on whitespace, then reverse.'),
  P(0,'First Unique Character','Hash maps','Find the index of the first character that appears exactly once. Print -1 if none exists.','One line containing a lowercase string.','One integer index.',[['leetcode','0'],['loveleetcode','2'],['aabb','-1']],'Count first, then scan again.'),
  P(0,'Running Sum','Arrays','Replace each number with the sum of all numbers up to and including it.','One line of space-separated integers.','The running sums on one line.',[['1 2 3 4','1 3 6 10'],['-2 5 -1','-2 3 2']],'Keep one accumulating total.'),
  P(0,'Valid Palindrome','Strings','Ignoring punctuation, spaces, and letter case, determine whether the text reads the same forwards and backwards. Only ASCII letters and digits count.','One line of text.','true or false in lowercase.',[['A man, a plan, a canal: Panama','true'],['race a car','false']],'Normalize the string before comparing.'),
  P(0,'Missing Number','Math','An array contains every integer from 0 through n except one. Find the missing value.','One line of distinct nonnegative integers; an empty line means n = 0.','The missing integer.',[['3 0 1','2'],['0 1','2'],['','0']],'Compare the expected sum with the actual sum.'),
  // Tuesday — foundations
  P(1,'Best Stock Trade','Arrays','Choose one day to buy and a later day to sell. Print the largest possible profit, or 0 if every trade loses money.','One line of daily prices.','Maximum profit.',[['7 1 5 3 6 4','5'],['7 6 4 3 1','0']],'Track the cheapest price so far.'),
  P(1,'Anagram Check','Strings','Decide whether two lowercase words contain the same characters with the same frequencies.','Two lines, one word per line.','true or false.',[['listen\nsilent','true'],['rat\ncar','false']],'Compare frequency counts.'),
  P(1,'Move Zeroes','Arrays','Move every zero to the end while preserving the order of nonzero values.','One line of integers.','The reordered integers on one line.',[['0 1 0 3 12','1 3 12 0 0'],['0 0 1','1 0 0']],'Collect nonzero values before appending zeroes.'),
  P(1,'Majority Element','Counting','Find the value that occurs more than half of the time. Such a value always exists.','One line of integers.','The majority value.',[['3 2 3','3'],['2 2 1 1 1 2 2','2']],'A candidate can cancel out a different value.'),
  P(1,'Intersection with Multiplicity','Hash maps','Print values found in both arrays, repeating each value as many times as it occurs in both. Sort the result in ascending order. If none, print an empty line.','Two lines of space-separated integers.','Sorted intersection on one line.',[['1 2 2 1\n2 2','2 2'],['4 9 5\n9 4 9 8 4','4 9']],'Use a frequency map for one array.'),
  P(1,'Longest Common Prefix','Strings','Find the longest prefix shared by every word. If there is no shared prefix, print an empty line.','One word per line.','The common prefix.',[['flower\nflow\nflight','fl'],['dog\nracecar\ncar','']],'Compare characters at the same position.'),
  // Wednesday — patterns
  P(2,'Longest Distinct Window','Sliding window','Find the length of the longest substring with no repeated characters.','One line of text.','One integer length.',[['abcabcbb','3'],['bbbbb','1'],['pwwkew','3']],'Move the left edge past a repeated character.'),
  P(2,'Product Except Self','Prefix sums','For each index, output the product of every other array value. Do not use division.','One line of integers.','Space-separated products.',[['1 2 3 4','24 12 8 6'],['-1 1 0 -3 3','0 0 9 0 0']],'Combine prefix and suffix products.'),
  P(2,'Subarray Sum Count','Prefix sums','Count contiguous subarrays whose sum equals k. Values may be negative.','Line 1: integers. Line 2: k.','One integer count.',[['1 1 1\n2','2'],['1 2 3\n3','2'],['1 -1 0\n0','3']],'A prefix sum identifies earlier matching prefixes.'),
  P(2,'Group Anagrams','Hash maps','Group words that are anagrams. Print one group per line. Sort words inside each group, then sort the group lines lexicographically.','One line of space-separated lowercase words.','Sorted groups, one line each.',[['eat tea tan ate nat bat','ate eat tea\nbat\nnat tan'],['ab ba abc','ab ba\nabc']],'Use each word’s sorted letters as a key.'),
  P(2,'Minimum Window Sum','Sliding window','Given positive integers and target s, find the minimum length of a contiguous subarray with sum at least s. Print 0 if none exists.','Line 1: positive integers. Line 2: target s.','One integer length.',[['2 3 1 2 4 3\n7','2'],['1 1 1\n5','0']],'Shrink the window while its sum still meets the target.'),
  P(2,'Rotate Array','Arrays','Rotate the array to the right by k positions. k may exceed the array length.','Line 1: integers. Line 2: nonnegative k.','Rotated array on one line.',[['1 2 3 4 5 6 7\n3','5 6 7 1 2 3 4'],['-1 -100 3 99\n2','3 99 -1 -100']],'Reduce k modulo array length.'),
  // Thursday — search and structure
  P(3,'Balanced Brackets','Stack','Determine whether a string of (), [], and {} brackets is correctly nested.','One line of bracket characters.','true or false.',[['({[]})','true'],['([)]','false'],['','true']],'Use a stack of opening brackets.'),
  P(3,'Search Insert Position','Binary search','In a sorted array of distinct integers, find the index of target, or the index where it should be inserted to stay sorted.','Line 1: sorted integers. Line 2: target.','Zero-based insertion index.',[['1 3 5 6\n5','2'],['1 3 5 6\n2','1'],['1 3 5 6\n7','4']],'Find the first value not less than target.'),
  P(3,'Daily Temperatures','Stack','For each day, find how many days until a strictly warmer temperature. Print 0 if there is no warmer future day.','One line of daily temperatures.','Space-separated waits.',[['73 74 75 71 69 72 76 73','1 1 4 2 1 1 0 0'],['30 40 50 60','1 1 1 0']],'Keep unresolved days on a monotonic stack.'),
  P(3,'Merge Intervals','Sorting','Merge every pair of overlapping closed intervals. Sort merged intervals by start. Intervals sharing an endpoint overlap.','One interval per line: start end.','Merged intervals, one per line.',[['1 3\n2 6\n8 10\n15 18','1 6\n8 10\n15 18'],['1 4\n4 5','1 5']],'Sort by start before merging.'),
  P(3,'Peak in Mountain','Binary search','A mountain array strictly increases and then strictly decreases. Find the index of its peak.','One line of integers, at least three.','Zero-based peak index.',[['0 2 1 0','1'],['0 10 5 2','1'],['0 1 2 3 1','3']],'Compare the middle value with the next one.'),
  P(3,'Next Greater Element','Stack','For each value, find the first strictly greater value to its right. Print -1 if there is none.','One line of integers.','Space-separated answers.',[['2 1 2 4 3','4 2 4 -1 -1'],['5 4 3','-1 -1 -1']],'Scan right to left with a decreasing stack.'),
  // Friday — dynamic programming
  P(4,'Climbing Steps','Dynamic programming','You can climb 1 or 2 steps at a time. Count distinct ways to reach step n. For n = 0, there is one way.','One nonnegative integer n, at most 45.','Number of ways.',[['2','2'],['5','8'],['0','1']],'Each step combines the previous two counts.'),
  P(4,'House Robber','Dynamic programming','Choose nonadjacent houses to maximize the total money. Skipping every house is allowed.','One line of nonnegative house values.','Maximum total.',[['1 2 3 1','4'],['2 7 9 3 1','12']],'At each house compare taking it with skipping it.'),
  P(4,'Coin Change','Dynamic programming','Given coin denominations and an amount, find the minimum number of coins needed. Every denomination can be reused. Print -1 if impossible.','Line 1: denominations. Line 2: target amount.','Minimum coin count or -1.',[['1 2 5\n11','3'],['2\n3','-1']],'Build answers from amount 0 upwards.'),
  P(4,'Longest Increasing Subsequence','Dynamic programming','Find the length of the longest strictly increasing subsequence. Values need not be adjacent.','One line of integers.','One integer length.',[['10 9 2 5 3 7 101 18','4'],['7 7 7 7','1']],'Keep the smallest possible tail for each length.'),
  P(4,'Unique Grid Paths','Dynamic programming','Count paths from the top-left to bottom-right of an m by n grid, moving only right or down. There are no obstacles.','One line: m n, both positive and at most 15.','Number of paths.',[['3 7','28'],['3 2','3']],'Each cell receives paths from above and left.'),
  P(4,'Decode Digits','Dynamic programming','Count ways to decode a string of digits using 1→A through 26→Z. A zero cannot stand alone.','One line of digits.','Number of decodings.',[['12','2'],['226','3'],['06','0']],'At each position, consider valid one- and two-digit endings.'),
  // Saturday — longer reasoning
  P(5,'Number of Islands','Graphs','Count connected groups of 1 cells in a binary grid. Cells connect only vertically and horizontally.','First line: rows columns. Then one row of 0/1 characters per line.','Number of islands.',[['4 5\n11110\n11010\n11000\n00000','1'],['4 5\n11000\n11000\n00100\n00011','3']],'Flood fill each unseen land cell.'),
  P(5,'Course Schedule','Graphs','There are n courses numbered 0 to n−1. Each later line a b means course a requires b first. Print whether every course can be finished.','First line: n. Remaining lines: prerequisite pairs a b.','true or false.',[['2\n1 0','true'],['2\n1 0\n0 1','false']],'A directed cycle makes completion impossible.'),
  P(5,'Kth Largest','Heaps','Find the kth largest value in an unsorted array. Equal values count separately.','Line 1: integers. Line 2: k, starting at 1.','The kth largest integer.',[['3 2 1 5 6 4\n2','5'],['3 2 3 1 2 4 5 5 6\n4','4']],'A size-k min heap keeps the largest k values.'),
  P(5,'Matrix Distance','Graphs','For every cell in a grid of 0s and 1s, output its Manhattan distance to the nearest 0. The grid contains at least one 0.','First line: rows columns. Then one space-separated grid row per line.','One space-separated distance row per line.',[['3 3\n0 0 0\n0 1 0\n1 1 1','0 0 0\n0 1 0\n1 2 1'],['2 2\n0 1\n1 1','0 1\n1 2']],'Start a breadth-first search from every zero at once.'),
  P(5,'Partition Equal Sum','Dynamic programming','Determine whether the integers can be split into two groups with equal sum. Every input value is positive.','One line of positive integers.','true or false.',[['1 5 11 5','true'],['1 2 3 5','false']],'Look for a subset with half the total sum.'),
  P(5,'Shortest Grid Route','Graphs','Find the shortest number of moves from S to E in a rectangular grid. # is a wall and . is open. Move up, down, left, or right. Print -1 if unreachable.','First line: rows columns. Then grid rows of S, E, #, and . characters.','Shortest move count or -1.',[['3 4\nS...\n##.#\n...E','5'],['2 3\nS##\n##E','-1']],'Breadth-first search finds the shortest path in an unweighted grid.'),
  // Sunday — challenge
  P(6,'Median of Two Sorted Arrays','Binary search','Find the median of two sorted integer arrays. Their combined length is at least one. Print an integer without a decimal point, or a value ending in .5. Aim for logarithmic time.','Two lines, one sorted array per line; either line may be empty.','The median.',[['1 3\n2','2'],['1 2\n3 4','2.5'],['\n1','1']],'Binary search a partition across the shorter array.'),
  P(6,'Regular Expression Match','Dynamic programming','Match the entire text against a pattern where . matches any single character and * matches zero or more of the preceding element. The pattern is valid.','Line 1: text. Line 2: pattern. Either may be empty.','true or false.',[['aab\nc*a*b','true'],['mississippi\nmis*is*p*.','false'],['ab\n.*','true']],'Let dp[i][j] describe matching text and pattern prefixes.'),
  P(6,'Word Ladder','Graphs','Change one letter at a time from start to end. Every intermediate word, including end, must be in the dictionary. Find the number of words in the shortest transformation sequence, or 0 if impossible. All words have equal length.','Line 1: start. Line 2: end. Remaining lines: dictionary words.','Sequence length or 0.',[['hit\ncog\nhot\ndot\ndog\nlot\nlog\ncog','5'],['hit\ncog\nhot\ndot\ndog\nlot\nlog','0']],'Breadth-first search over words differing by one letter.'),
  P(6,'Trapping Rain Water','Two pointers','Given bar heights of width 1, compute how many units of rainwater remain between the bars after raining.','One line of nonnegative bar heights.','Total trapped water.',[['0 1 0 2 1 0 1 3 2 1 2 1','6'],['4 2 0 3 2 5','9']],'Water above a bar depends on the highest wall on each side.'),
  P(6,'Edit Distance','Dynamic programming','Find the fewest insertions, deletions, or replacements required to transform the first word into the second. Either word may be empty.','Two lines, one word per line.','Minimum operation count.',[['horse\nros','3'],['intention\nexecution','5'],['\nabc','3']],'Compare prefixes and their last characters.'),
  P(6,'Largest Rectangle in Histogram','Stack','Find the largest rectangular area formed by adjacent bars in a histogram. Every bar has width 1.','One line of nonnegative heights.','Maximum area.',[['2 1 5 6 2 3','10'],['2 4','4'],['1 1 1','3']],'A monotonic stack reveals each bar’s widest span.'),
];
export const weekdays = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export function problemForDate(date) {
  const day = (date.getDay() + 6) % 7;
  const localDay = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const epoch = Date.UTC(2026, 0, 5); // Monday; UTC arithmetic avoids daylight-saving drift.
  const week = Math.floor((localDay - epoch) / 604800000);
  const pool = problems.filter(p => p.day === day);
  return { problem: pool[((week % pool.length) + pool.length) % pool.length], day, week };
}
